# Q1. Ans

Yes, there is a difference in the data type of the variables list_ and array_list.

The variable list_ is a Python list, which can hold elements of different data types. In this case, the elements in the list are strings.

The variable array_list is a NumPy array created using np.array(). NumPy arrays are homogeneous, meaning they can only hold elements of the same data type. In this case, since all the elements in the list are strings, the array will have a data type of string as well.

To print the data types of both variables, you can use the type() function:

In [1]:
print(type(list_))
print(type(array_list))


NameError: name 'list_' is not defined

# Q2. Ans

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print the data type of each element in list_
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Ans

Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list after the change.

By specifying dtype=int when creating array_list, the elements in array_list will be converted to integers. The original elements in list_ were strings, but now they will be converted to integers.

To print the data types of each element in both variables list_ and array_list, you can use a loop along with the type() function. Here's an example code:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Print the data type of each element in list_
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Q4. Ans

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) shape
print("Shape:", num_array.shape)

# (ii) size
print("Size:", num_array.size)


Shape: (2, 3)
Size: 6


# Q5. Ans

In [5]:
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Ans

In [6]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
